import turtle

t = turtle.Turtle()

def cuadrado(color):
    t.pencolor(color)
    t.fillcolor(color)
    t.begin_fill()
    t.seth(0)
    t.forward(30)
    t.seth(90)
    t.forward(30)
    t.seth(180)
    t.forward(30)
    t.seth(270)
    t.forward(30)
    t.end_fill()
    
def cuadritos():
    tamaño = 10
    t.pencolor("black")
    t.fillcolor("gold")
    t.begin_fill()
    t.seth(0)
    t.forward(tamaño)
    t.seth(90)
    t.forward(tamaño)
    t.seth(180)
    t.forward(tamaño)
    t.seth(270)
    t.forward(tamaño)
    t.end_fill()
    
def go(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
    
t.pencolor("red")
t.fillcolor("red")
go(-30, -180)
t.begin_fill()
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(120)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(-90)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(-90)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(-120)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(-30)
t.seth(0)
t.forward(30)
t.end_fill()

go(-30, -210)
cuadrado("black")
go(0, -180)
cuadrado("black")
go(30, -150)
cuadrado("black")
go(60, -120)
cuadrado("black")
go(90, -90)
cuadrado("black")
go(120, -60)
cuadrado("black")

t.pencolor("black")
t.fillcolor("black")
go(150, -30)
t.begin_fill()
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(120)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(-120)
t.end_fill()

go(120, 90)
cuadrado("black")

go(120, 120)
t.begin_fill()
t.seth(0)
t.forward(-90)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(90)
t.seth(90)
t.forward(-30)
t.end_fill()

go(0, 90)
cuadrado("black")
go(-30, 60)
cuadrado("black")
go(-60, 90)
cuadrado("black")

go(-60, 120)
t.begin_fill()
t.seth(0)
t.forward(-90)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(90)
t.seth(90)
t.forward(-30)
t.end_fill()

go(-180, 90)
cuadrado("black")

go(-210, -30)
t.begin_fill()
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(120)
t.seth(0)
t.forward(-30)
t.seth(90)
t.forward(-120)
t.end_fill()

go(-180, -60)
cuadrado("black")
go(-150, -90)
cuadrado("black")
go(-120, -120)
cuadrado("black")
go(-90, -150)
cuadrado("black")
go(-60, -180)
cuadrado("black")

go(-150, -30)
cuadrado("white")

t.pencolor("white")
t.fillcolor("white")
go(-150, 30)
t.begin_fill()
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(30)
t.seth(90)
t.forward(30)
t.seth(0)
t.forward(-60)
t.seth(90)
t.forward(-60)
t.end_fill()

x_inicio = -75
y_inicio = -40
tamaño = 10
t.pencolor("black")
t.fillcolor("gold")
go(x_inicio, y_inicio)
t.begin_fill()
t.seth(0)
t.forward(tamaño)
t.seth(90)
t.forward(tamaño*5)
t.seth(0)
t.forward(tamaño*2)
t.seth(90)
t.forward(tamaño)
t.seth(0)
t.forward(-tamaño*5)
t.seth(90)
t.forward(-tamaño)
t.seth(0)
t.forward(tamaño*2)
t.seth(90)
t.forward(-tamaño*5)
t.end_fill()

go(x_inicio + tamaño*4, y_inicio)
t.begin_fill()
t.seth(0)
t.forward(tamaño)
t.seth(90)
t.forward(tamaño*6)
t.seth(0)
t.forward(-tamaño)
t.seth(90)
t.forward(-tamaño*6)
t.end_fill()

go(x_inicio + tamaño*5, y_inicio + tamaño*3)
cuadritos()
go(x_inicio + tamaño*6, y_inicio + tamaño*4)
cuadritos()
go(x_inicio + tamaño*7, y_inicio + tamaño*5)
cuadritos()
go(x_inicio + tamaño*6, y_inicio + tamaño*2)
cuadritos()

go(x_inicio + tamaño*7, y_inicio)
t.begin_fill()
t.seth(0)
t.forward(tamaño)
t.seth(90)
t.forward(tamaño*2)
t.seth(0)
t.forward(-tamaño)
t.seth(90)
t.forward(-tamaño*2)
t.end_fill()

go(x_inicio + tamaño*9, y_inicio)
t.begin_fill()
t.seth(0)
t.forward(tamaño)
t.seth(90)
t.forward(tamaño*6)
t.seth(0)
t.forward(-tamaño)
t.seth(90)
t.forward(-tamaño*6)
t.end_fill()

go(x_inicio + tamaño*13, y_inicio)
t.begin_fill()
t.seth(0)
t.forward(tamaño)
t.seth(90)
t.forward(tamaño*6)
t.seth(0)
t.forward(-tamaño)
t.seth(90)
t.forward(-tamaño*6)
t.end_fill()

go(x_inicio + tamaño*10, y_inicio + tamaño*4)
cuadritos()
go(x_inicio + tamaño*11, y_inicio + tamaño*3)
cuadritos()
go(x_inicio + tamaño*12, y_inicio + tamaño*4)
cuadritos()

t.hideturtle()
turtle.done()